---
- name: set-cluster
  shell: >
      kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ k8s_lb_ip }}:6443 \
      --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
  loop: "{{ groups['k8s_node'] }}"
  become: yes
  become_user: "{{ local_id }}"
  
- name: set-credentials
  shell: >
      kubectl config set-credentials system:node:{{ item }} \
      --client-certificate={{ item }}.pem \
      --client-key={{ item }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    #creates: "{{ k8s_conf_files_dir }}/{{ item }}.kubeconfig"
  loop: "{{ groups['k8s_node'] }}"

- name: set-context
  shell: >
      kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=system:node:{{ item }} \
      --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    #creates: "{{ k8s_conf_files_dir }}/
  loop: "{{ groups['k8s_node'] }}"

- name: use-context
  shell:
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    cmd: kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  loop: "{{ groups['k8s_node'] }}"
