---
# add symlink to /usr/bin/pip3
- name: Install and configure Docker
  include_role:
    name: docker

- name: Gather instance facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['k8s_controller'] }}"

- name: Create HA Proxy container conf dir (root)
  file:
    path: "{{ hap_conf_dir }}"
    state: directory

- name: Create HA Proxy container conf sub dirs
  file:
    path: "{{ hap_conf_dir }}/{{ item }}"
    state: directory
  loop: "{{ hap_sub_dirs }}"

- name: Create HA Proxy conf file
  template:
    src: "./kube_lb.j2"
    dest: "{{ hap_conf_dir}}/{{ hap_conf_file }}"
    owner: vagrant
    group: docker
    trim_blocks: no

- name: Create HA Proxy container
  docker_container:
    name: "{{ hap_container_name }}"
    image: "{{ hap_container_image }}"
    published_ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - "0.0.0.0:{{ hap_port }}:{{ hap_port }}"
    restart_policy: always
    healthcheck:
      interval: "10000"
    volumes:
      - "{{ hap_conf_dir }}:/usr/local/etc/haproxy:ro"
