---
- name: Get hosts for etcd initial cluster
  set_fact:
    k8sEtcdHosts: >-
      {% set comma = joiner(",") %}{% for item in groups['k8s_etcd'] -%}
        {{ comma() }}{{ item }}=https://{{ hostvars[item]["ansible_"+hostvars[item]["private_if"]].ipv4.address }}:2380
      {%- endfor %}

- name: Output of hostnames/IPs used for etcd initial cluster
  debug: var=k8sEtcdHosts

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - /var/lib/etcd
  - /etc/etcd

- name: Copy etcd certs
  copy:
    src: "{{ k8s_conf_files_dir }}/{{ item }}"
    dest: /etc/etcd
  loop:
  - etcd-key.pem
  - etcd.pem
  - ca.pem

- name: Download etcd archive file
  get_url:
    url: http://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: "/tmp/"

- name: Extract etcd archive file
  unarchive:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    remote_src: yes
    dest: /usr/local/bin
    extra_opts: [--strip-components=1]
  notify:
  - Restart etcd service

#- name: Delete etcd archive
#  file:
#    path: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
#    state: absent

- name: Create etcd unit file
  template:
    src: ../templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
  - Reload systemd units
  - Restart etcd service

- name: Enable and start etcd service
  systemd:
    name: etcd
    enabled: yes
    state: started
