---
# handlers file for k8s-node
- name: Reload systemd units
  systemd:
    daemon_reload: yes

- name: List kube dns pods
  shell:
    cmd: kubectl --kubeconfig /var/lib/kubernetes/admin.kubeconfig get pods -l k8s-app=kube-dns -n kube-system

# Kube Proxy
- name: Restart kube proxy service
  ansible.builtin.service:
    name: kube-proxy
    state: restarted

# Kubelet
- name: Restart kubelet service
  ansible.builtin.service:
    name: kubelet
    state: restarted

# CNI
- name: Extract cni plugins
  unarchive:
    src: "/tmp/{{ archives.cni_plugins.file }}"
    remote_src: yes
    dest: /opt/cni/bin
    extra_opts: [--strip-components=1]

# containerd
- name: Set owner on containerd binaries
  file:
    state: file
    path: "{{ item }}"
    owner: root
    group: root
  with_fileglob:
  - "/bin/container*"
  - "/bin/ctr"

- name: Extract containerd
  unarchive:
    src: "/tmp/{{ archives.containerd.file }}"
    remote_src: yes
    dest: /bin
    extra_opts: [--strip-components=1]
  notify: Set owner on containerd binaries

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted