---
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

- name: ensure /etc/containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    # mode: u=rw,g=r,o=r
    # owner: root
    # group: root

## Prerequisites
# - name: ensure containerd.conf file exists
#   ansible.builtin.file:
#     path: /etc/modules-load.d/containerd.conf
#     state: touch
    # mode: u=rw,g=r,o=r
    # owner: root
    # group: root
    # access_time: preserve
    # modification_time: preserve

# - name: containerd.conf contents
#   lineinfile:
#     path: /etc/modules-load.d/containerd.conf
#     line: "{{ item }}"
#   loop: 
#     - overlay
#     - br_netfilter

- name: containerd kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  notify: Restart containerd service

- name: Manage sysctl entries for cri
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

# Install containerd from package or binary
- name: Install containerd (package)
  import_tasks: containerd_pkg.yml
  when: oci_installer == 'package'

- name: Install containerd (binary)
  import_tasks: containerd_bin.yml
  when: oci_installer == 'binary'

# Configure containerd
# Restart containerd
- name: Create containerd config
  template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
  notify: Restart containerd service

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started