---
- name: Download kube node binaries
  get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    mode: "0750"
  loop: "{{ downloads }}"

- name: Download cri tools
  get_url:
    url: "{{ archives.cri_tools.url }}"
    dest: "/tmp/{{ archives.cri_tools.file }}"
    
- name: Extract cri tools
  unarchive:
    src: "/tmp/{{ archives.cri_tools.file }}"
    remote_src: yes
    dest: /usr/local/bin
    extra_opts: [--strip-components=1]

#- name: Delete cri tools archive
#  file:
#    path: "{{ item }}"
#    state: absent
#  loop:
#    - "/tmp/{{ archives.cri_tools.file }}"
