---
- name: Install kube-apiserver binary
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-apiserver"
    dest: /usr/local/bin
    mode: u=rx,g=rx,o=r
    owner: root
    group: root

- name: Install kube-controller-manager binaries
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-controller-manager"
    dest: /usr/local/bin
    mode: u=rx,g=rx,o=r
    owner: root
    group: root

- name: Install kube-scheduler binaries
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-scheduler"
    dest: /usr/local/bin
    mode: u=rx,g=rx,o=r
    owner: root
    group: root
