---
# defaults file for oci
oci_spec: containerd
oci_image_regstry_address: "https://registry-1.docker.io"
oci_installer: binary # package or binary

# defaults if using containerd oci
oci_containerd_version: "1.3.6"
oci_containerd_file: "containerd-{{ oci_containerd_version }}-{{ oci_os }}-{{ oci_arch }}.tar.gz"
oci_containerd_url: "https://github.com/containerd/containerd/releases/download/v{{ oci_containerd_version }}/containerd-{{ oci_containerd_version }}-{{ oci_os }}-{{ oci_arch }}.tar.gz"

# will use current system os and arch from ansible facts - if running against remote system with different os or arch, pass the value(s) manually instead
oci_os: "linux" # "{{ ansible_system|lower }}"
oci_arch: "amd64" # "{{ cpu_arch[ansible_architecture] }}"